import { useState } from 'react'

export function DemoBanner() {
  const [dismissed, setDismissed] = useState(() => sessionStorage.getItem('cw_banner_dismissed') === '1')

  if (dismissed) return null

  return (
    <div className="demo-banner">
      <span>
        <strong>Demo telemetry</strong> — every metric, log line, alert and incident on this page is generated by a
        built-in simulator modeling realistic traffic and failure patterns. Nothing here comes from a real
        production fleet.
      </span>
      <button
        onClick={() => {
          sessionStorage.setItem('cw_banner_dismissed', '1')
          setDismissed(true)
        }}
        aria-label="Dismiss"
      >
        ×
      </button>
    </div>
  )
}
